### ISSUE TITLE
Waagent still tries to run on Hyper-V locally

### ISSUE THREAD

**Issue by GurliGebis** [truenas/middleware#8113]
I just did a clean install on a fresh local Hyper-V VM, using the latest TrueNAS SCALE nightly ISO, and it tries to start waagent on startup, so it looks like this is still broken (the PR from #8023 seems to not be enough).

I think the best solution is to remove waagent entirely, and let people that wants to run it in Azure install it using the Azure extension.

Upsteam for waagent says it should only be installed when running in Azure, so that would be the recommended solution I think.

**Comment by sonicaj** [comment]
We are disabling it by default and interested users can enable it as desired. Thank you for testing it out on local Hyper-V!

**Comment by GurliGebis** [comment]
Thank you - I'll give it another try with a nightly ISO in a few days :)

**Comment by GurliGebis** [comment]
@sonicaj I just tried the latest nightly ISO, and now it boots fine.
However, waagent is still running and spamming with the original error with trying to mount the dvd.
So it sounds like it is still installed and gets started somehow.

**Comment by sonicaj** [comment]
@GurliGebis can you please confirm if you upgraded or tried a fresh install ?

**Comment by GurliGebis** [comment]
@sonicaj Fresh install from this ISO: https://download.truenas.com/truenas-scale-nightly/TrueNAS-SCALE-22.02-MASTER-20220111-100451.iso

**Comment by GurliGebis** [comment]
Let me know if you would like me to send a screenshot of the console

**Comment by sonicaj** [comment]
@GurliGebis can you please try the nightlies again after a couple of days ? We should be good to go
```
❯ systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
     Loaded: loaded (/lib/systemd/system/walinuxagent.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
```

**Comment by GurliGebis** [comment]
I'll give it a go on friday and see :)

**Comment by GurliGebis** [comment]
@sonicaj I can confirm that it is working with the latest nightly ISO.
Thanks for fixing the issue, now it looks to be working as expected on Hyper-V 😊
