### ISSUE TITLE
Actions buttons should be disabled after a first click

### ISSUE THREAD

**Issue by maisim** [truenas/middleware#8458]
![image](https://user-images.githubusercontent.com/6648433/157223514-1080e3c2-62ff-45ac-b941-7137a347ff41.png)

If by mistake you click twice on a button (like save button on app creation), it throw an exception.
Even if things run well in background this can be disturbing for the user.

**Comment by stavros-k** [comment]
iX does not look in github issues. 
Use https://jira.ixsystems.com/login.jsp

**Comment by yocalebo** [comment]
Please open a ticket at `https://jira.ixsystems.com` please 😄
