### ISSUE TITLE
CloudSync custom flags

### ISSUE THREAD

**Issue by DeltaByte** [truenas/middleware#8931]
Would it be possible to support adding custom flags on CloudSync tasks? I was thinking it might be easiest to support a simple key/value method for adding this so that users themselves can add any rclone flags needed depending on their provider without you folks having to actually maintain specific definitions for them.

In my case I only actually need to add `--drive-acknowledge-abuse=true` for my GDrive task, but I figure allowing people to tune it themselves if needed is probably better.

I'm not overly familiar with Python, but if you're happy with it then I can probably create a PR to implement it myself if needs be.

**Comment by yocalebo** [comment]
@DeltaByte thanks for opening up an issue. We don't monitor github issues so please open a ticket at `https://jira.ixsystems.com`.
